#!/bin/bash

NODE_VER="node-10.12.0"

function command_exists {
  #this should be a very portable way of checking if something is on the path
  #usage: "if command_exists foo; then echo it exists; fi"
  type "$1" &> /dev/null
}

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  TARGET="$(readlink "${SOURCE}")"
  if [[ $SOURCE == /* ]]; then
    SOURCE="${TARGET}"
  else
    DIR="$( dirname "${SOURCE}" )"
    SOURCE="{$DIR}/${TARGET}" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  fi
done

SOAJS_INSTALLER="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"

#location of /usr/bin based on operating system
BINLOCATION=''

# check the platform to determine which node to use: linux | darwin
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then

	# install make, it is needed
	apt-get install -y make

	BINLOCATION='/usr/bin'
	NODE_LOCATION="$NODE_VER/node-linux-x64"

elif [[ "$unamestr" == 'Darwin' ]]; then
	BINLOCATION='/usr/local/bin'
	NODE_LOCATION="$NODE_VER/node-darwin-x64"
	if [ ! -d "${BINLOCATION}" ]; then
        mkdir -p ${BINLOCATION}
    fi
fi

if command_exists git; then
    pushd ${BINLOCATION} > /dev/null 2>&1

    rm -f soajs
    echo "Creating soajs command @: ${BINLOCATION}"
    ln -s ${SOAJS_INSTALLER}/bin/soajs .

    if [ ! -e node ]; then
        rm -f node
        echo "Creating node command @: ${BINLOCATION}"
        ln -s ${SOAJS_INSTALLER}/include/${NODE_LOCATION}/bin/node .
    fi

    pushd ${SOAJS_INSTALLER} > /dev/null 2>&1

	NPM_LOCATION=${SOAJS_INSTALLER}/node_modules/npm/bin/npm-cli.js

	if [ -d ${SOAJS_INSTALLER}/node_modules/soajs.installer.local ]; then
		rm -Rf ${SOAJS_INSTALLER}/node_modules/soajs.installer.local
	fi
	if [ -d ${SOAJS_INSTALLER}/node_modules/soajs.installer.remote ]; then
		rm -Rf ${SOAJS_INSTALLER}/node_modules/soajs.installer.remote
	fi
	if [ -d ${SOAJS_INSTALLER}/node_modules/soajs.installer.versions ]; then
		rm -Rf ${SOAJS_INSTALLER}/node_modules/soajs.installer.versions
	fi
	if [ -d soajs.installer.local ]; then
		rm -Rf soajs.installer.local
	fi
	if [ -d soajs.installer.remote ]; then
		rm -Rf soajs.installer.remote
	fi
	if [ -d soajs.installer.versions ]; then
		rm -Rf soajs.installer.versions
	fi

    ${NPM_LOCATION} install soajs.installer.local
    ${NPM_LOCATION} install soajs.installer.remote
    ${NPM_LOCATION} install soajs.installer.versions

    mv ${SOAJS_INSTALLER}/node_modules/soajs.installer.local .
    mv ${SOAJS_INSTALLER}/node_modules/soajs.installer.remote .
    mv ${SOAJS_INSTALLER}/node_modules/soajs.installer.versions .

    echo "Done successfully"
else

    echo "You need to install git and re-run ./INSTALL again"
fi