#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  TARGET="$(readlink "$SOURCE")"
  if [[ $SOURCE == /* ]]; then
    SOURCE="$TARGET"
  else
    DIR="$( dirname "$SOURCE" )"
    SOURCE="$DIR/$TARGET" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  fi
done

SOAJS_INSTALLER="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

#location of /usr/bin based on operating system
$BINLOCATION=''

# check the platform to determine which node to use: linux | darwin
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then

	# install make, it is needed
	apt-get install -y make

	$BINLOCATION='/usr/bin'
	NODE_LOCATION="node-8.12.0/node-linux-x64"

elif [[ "$unamestr" == 'Darwin' ]]; then
	$BINLOCATION='/usr/local/bin'
	NODE_LOCATION="node-8.12.0/node-darwin-x64"

fi

pushd $$BINLOCATION

echo "Linking SOAJS Installer: "
if [ -e soajs ]
then
	echo "soajs installer already linked to your $$BINLOCATION"
else
	echo "Linking soajs installer to your $$BINLOCATION"
	ln -s $SOAJS_INSTALLER"/bin/soajs" .
fi

echo "Linking NodeJS: "
if [ -e node ]
then
	echo "nodejs already linked to your $$BINLOCATION"
else
	echo "Linking nodejs installer to your $$BINLOCATION"
	ln -s $SOAJS_INSTALLER"/include/"$NODE_LOCATION"/bin/node" .
fi