#!/bin/bash

NODE_VER="node-10.12.0"

function command_exists {
  #this should be a very portable way of checking if something is on the path
  #usage: "if command_exists foo; then echo it exists; fi"
  type "$1" &> /dev/null
}

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  TARGET="$(readlink "${SOURCE}")"
  if [[ $SOURCE == /* ]]; then
    SOURCE="${TARGET}"
  else
    DIR="$( dirname "${SOURCE}" )"
    SOURCE="{$DIR}/${TARGET}" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  fi
done

SOAJS_INSTALLER="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"


if command_exists git; then

    pushd ${SOAJS_INSTALLER} > /dev/null 2>&1
	rm -rf soajs.installer.local
	git clone https://github.com/soajs/soajs.installer.local.git
	rm -rf soajs.installer.remote
	git clone https://github.com/soajs/soajs.installer.remote.git
	rm -rf soajs.installer.versions
	git clone https://github.com/soajs/soajs.installer.versions.git

    echo "Done successfully"
else

    echo "You need to install git and re-run ./INSTALL again"
fi